export const CHANGE_RECOMMEND_BANER = 'recommend/CHANGE_BANER';
export const CHANGE_RECOMMEND_HOTRECOMMEND = 'recommend/CHANGE_HOTRECOMMEND';
export const CHANGE_RECOMMEND_ALBUM = 'recommend/CHANGE_ALBUM';